@URL = http://localhost:8080 
# @URL =  https://rest-server-basic.onrender.com

### get request
GET {{URL}}/api/users?id=32432

### post request
POST {{URL}}/api/users
content-type: application/json

{
    "name": "Henry Gustav1",
    "google": true,
    "email": "test558@gmail.com",
    "password": "123256",
    "role": "VENTAS_ROLE"
}

### delete user
DELETE {{URL}}/api/users

### put request
PUT {{URL}}/api/users/10?q=hello&name=Henry&apiKey=12383280