# @URL = http://localhost:8080 
@URL =  https://rest-server-basic.onrender.com

### get request
GET {{URL}}/api/users

### get request limit
GET {{URL}}/api/users?limit=cdsfdcw&skip=5

### post request
POST {{URL}}/api/users
content-type: application/json

{
    "name": "Henry Gustav16",
    "google": true,
    "email": "test16@gmail.com",
    "password": "123256",
    "role": "VENTAS_ROLE"
}

### delete user
DELETE {{URL}}/api/users/65134a0acfca4f8277deebe2

### put request
PUT {{URL}}/api/users/65130c645ea7136d7d3e168f
content-type: application/json

{
    "name": "Henry Gustav2-**--",
    "google": true,
    "email": "test559@gmail.com@@@-",
    "password": "123256",
    "role": "VENTAS_ROLE"
}
